version: '3.3'

services:
  messaging:
    container_name: 'messaging'
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    networks:
      - messaging-network
    volumes:
      - ./:/messaging

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - messaging-network

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=messagingdb
    ports:
      - "5432:5432"
    networks:
      - messaging-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - messaging-network

networks:
  messaging-network:
    driver: bridge
